# 窗口大小
GRID_WIDTH=28
GRID_HEIGHT=31
GRID_CELL_SIZE=20

SCREEN_WIDTH = GRID_WIDTH*GRID_CELL_SIZE
SCREEN_HEIGHT = GRID_HEIGHT*GRID_CELL_SIZE

# 音量
SFX_VOLUME = 0.7
BGM_VOLUME = 0.5

# 帧率
FPS = 60

# 玩家参数
PLAYER_SIZE = (16, 16)  # 玩家大小
PLAYER_SPEED = 4  # 玩家速度
PLAYER_LIVES = 3  # 玩家生命条数
PLAYER_INVINCIBLE_TIME = 3000  # 玩家无敌时间

# 敌人参数
ENEMY_SIZE = (16, 16)  # 敌人大小
ENEMY_SPEED = 2  # 敌人速度
ENEMY_NUM = 10  # 敌人数量
ENEMY_CHANGE_DIRECTION_INTERVAL=5000

# 水果参数
FRUIT_SIZE = (16, 16)  # 水果大小
FRUIT_NUM = 240  # 水果数量
